### ISSUE TITLE
[BUG] ClassNotFoundException: org.apache.avro.Schema$Parser

### ISSUE THREAD

**Issue by mgusek-interhyp** [CoffeeBeansLabs/azure-kafka-connector#74]
**Describe the bug**
Testing plugin runs in a ClassNotFoundException

**To Reproduce**
Here's my config:
```
class: io.coffeebeans.connect.azure.blob.sink.AzureBlobSinkConnector
config:
  azblob.connection.string: <hidden>
  azblob.container.name: <some_container>
  flush.size: 9000
  format: AVRO
  key.converter: org.apache.kafka.connect.json.JsonConverter
  key.converter.schemas.enable: false
  partition.strategy: DEFAULT
  topics: <some_topics>
  value.converter: org.apache.kafka.connect.json.JsonConverter
  value.converter.basic.auth.credentials.source: USER_INFO
  value.converter.basic.auth.user.info: <hidden>
  value.converter.schema.registry.url: 'http://registry.axample.com:8080'
  value.converter.schemas.enable: false
tasksMax: 2
```

**Error log**

```
kafka/micro-eh-dwe-aks-connect-6d947bbc9c-jklzb[micro-eh-dwe-aks-connect]:  (io.coffeebeans.connect.azure.blob.sink.config.AzureBlobSinkConfig) [task-thread-devpros-3503-configuration-0]
kafka/micro-eh-dwe-aks-connect-6d947bbc9c-jklzb[micro-eh-dwe-aks-connect]: 2023-06-29 08:57:50,458 ERROR [devpros-3503-configuration|task-0] WorkerSinkTask{id=devpros-3503-configuration-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask) [task-thread-devpros-3503-configuration-0]
kafka/micro-eh-dwe-aks-connect-6d947bbc9c-jklzb[micro-eh-dwe-aks-connect]: java.lang.NoClassDefFoundError: org/apache/avro/Schema$Parser
kafka/micro-eh-dwe-aks-connect-6d947bbc9c-jklzb[micro-eh-dwe-aks-connect]:      at io.coffeebeans.connect.azure.blob.sink.format.avro.AvroSchemaStore.<init>(AvroSchemaStore.java:30)
kafka/micro-eh-dwe-aks-connect-6d947bbc9c-jklzb[micro-eh-dwe-aks-connect]:      at io.coffeebeans.connect.azure.blob.sink.format.avro.AvroSchemaStore.getSchemaStore(AvroSchemaStore.java:40)
kafka/micro-eh-dwe-aks-connect-6d947bbc9c-jklzb[micro-eh-dwe-aks-connect]:      at io.coffeebeans.connect.azure.blob.sink.AzureBlobSinkTask.getSchemaStore(AzureBlobSinkTask.java:271)
kafka/micro-eh-dwe-aks-connect-6d947bbc9c-jklzb[micro-eh-dwe-aks-connect]:      at io.coffeebeans.connect.azure.blob.sink.AzureBlobSinkTask.start(AzureBlobSinkTask.java:70)
kafka/micro-eh-dwe-aks-connect-6d947bbc9c-jklzb[micro-eh-dwe-aks-connect]:      at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:312)
kafka/micro-eh-dwe-aks-connect-6d947bbc9c-jklzb[micro-eh-dwe-aks-connect]:      at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:187)
kafka/micro-eh-dwe-aks-connect-6d947bbc9c-jklzb[micro-eh-dwe-aks-connect]:      at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:244)
kafka/micro-eh-dwe-aks-connect-6d947bbc9c-jklzb[micro-eh-dwe-aks-connect]:      at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
kafka/micro-eh-dwe-aks-connect-6d947bbc9c-jklzb[micro-eh-dwe-aks-connect]:      at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
kafka/micro-eh-dwe-aks-connect-6d947bbc9c-jklzb[micro-eh-dwe-aks-connect]:      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
kafka/micro-eh-dwe-aks-connect-6d947bbc9c-jklzb[micro-eh-dwe-aks-connect]:      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
kafka/micro-eh-dwe-aks-connect-6d947bbc9c-jklzb[micro-eh-dwe-aks-connect]:      at java.base/java.lang.Thread.run(Thread.java:833)
kafka/micro-eh-dwe-aks-connect-6d947bbc9c-jklzb[micro-eh-dwe-aks-connect]: Caused by: java.lang.ClassNotFoundException: org.apache.avro.Schema$Parser
```

**Additional context**
Kafka connect is managed by Strimzi, running on Kubernetes.
Kafka + Kafka connect version: 3.3.2
I'm getting the same error with `format: JSON` and no schema registry
